name: GNN_project
channels:
  - defaults
  - conda-forge
  - pyg
dependencies:
  - python=3.9
  - numpy
  - networkx
  - ipykernel
  - matplotlib
  - pandas
  - gensim
  - transformers
  - pyg
  - python-magic
  - ultralytics
  - opencv
  - nltk
  - pip
  - pip:
    - contractions
